# Generated by Django 6.0.6 on 2026-06-06 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.duty')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.exam')),
                ('last_edited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='duty',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duties', to='core.machine'),
        ),
        migrations.AddField(
            model_name='duty',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='core.problem'),
        ),
    ]
