# Generated by Django 6.0.6 on 2026-06-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='cost',
        ),
    ]
