# Generated by Django 6.0.6 on 2026-06-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_machine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='nurse',
        ),
    ]
