# Generated by Django 6.0.6 on 2026-06-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_requested',
            field=models.BooleanField(default=False),
        ),
    ]
